### PR TITLE
Add Simplified Chinese locale

### PR DESCRIPTION
**Pull request by cpunion**
Add Simplified Chinese, and fallback to base locale to compatible zh-CN/en-US locales with flatpickr.
 
Since #99, I can't test it in flatpickr, just check the generated code.

### CODE REVIEW

**Comment by cpunion** [comment]
Ahh... Is this project alive?

I love this project, better than active-admin for UI, bootstrap, and very easy to customize.

**Comment by spohlenz** [comment]
@cpunion This project is definitely alive. I haven't had a chance yet to fully review your PR and other issue (I'd like to see if we can handle the I18n fallbacks better). However I do appreciate your contribution and will hopefully have it merged soon.

**Comment by cpunion** [comment]
@spohlenz Great! Thanks for your quick response.

**Comment by spohlenz** [comment]
I have cherry-picked the translation file commit and implemented an alternative method for the Flatpickr fallbacks. Thank you again for the PR.

**Pull request closed without merging**
