### PR TITLE
Assets update (new build process, Bootstrap 4, FontAwesome 5)

### PR DESCRIPTION
**Pull request by spohlenz**
Long overdue, this PR updates Trestle to Bootstrap 4 as well as updating other asset dependencies to the latest available versions (e.g. FontAwesome to v5). In the process, it introduces a new Webpack-based build system that generates a static JS/CSS bundle, eliminating the need for the run-time dependencies on Sass and Autoprefixer. Sass is still required for custom theme compilation, but it is now possible to use sassc-rails instead.

Since this is a fairly major update that can impact existing app and plugin code, it will be released as version 0.9.0 once any issues are ironed out.

If you would like to test this out now, use the `bootstrap4` branch of trestle, as well as the corresponding `bootstrap4` branches for trestle-auth and trestle-search.

## Summary of changes

- [x] Implement new build process using Webpack
- [x] Clean up and restructure CSS and JS (moved to `/frontend`)
- [x] Update Bootstrap and other dependencies
- [x] Switch from jquery-ujs to rails-ujs
- [x] Extract theme CSS (`/frontend/theme`) and only include when Sass is available
- [x] Update helpers to use Bootstrap 4 classes
- [x] Introduce new card helper and deprecate panel and well helpers
- [x] Remove Ionicons icon pack
- [x] Remove dependencies on sass-rails and autoprefixer-rails

## Why not use Webpacker?

Webpacker is promising, and as Rails evolves further away from Sprockets will likely be something that I migrate to in future (hopefully with less pain). However the support for engine assets is currently fairly immature, and so isn't currently a good fit. I'd also like to retain support for older applications for as long as possible.

### CODE REVIEW

**Comment by tjk** [comment]
Is it possible to assist this in any way? Just discovered trestle and it's awesome except initial render is taking 40+ seconds... Please let me know if I should open an issue because perhaps something else is misconfigured.

**Comment by spohlenz** [comment]
@tjk I'm definitely keen to get this merged in fairly soon, so if you have an existing Trestle project, it'd be great if you could test out this branch and let me know if it improves that initial render time and if you encounter any issues with backwards compatibility.

**Comment by samnymr** [comment]
@spohlenz Are you any closer with this? can I help in any way, keen for this!

**Comment by spohlenz** [comment]
@samnymr My plan is to definitely merge this within the next few weeks, as I have some contracts finishing up that will open up some time for more Trestle development.

I have been running this branch in production for a couple of projects, which has been working well. If you are able to test out this branch also and let me know how you go (good or bad), then that would definitely be helpful.

**Comment by samnymr** [comment]
@spohlenz We do have a test branch, I'll see if I can find any issues and let you know over the next couple of days 👍

**Comment by tjk** [comment]
(FYI been using this branch in production for a while and it's definitely an improvement over master)

**Comment by teohm** [comment]
@tjk To use the branch for a new production app, any changes needed on the installation / configuration steps?

@spohlenz Aside from the branch conflicts, any pending work before we can merge this into master?

**Comment by spohlenz** [comment]
@teohm:

> To use the branch for a new production app, any changes needed on the installation / configuration steps?

For a new app, everything should be the same. The `trestle:install` generator will generate a few SCSS files slightly differently from what is in master (`_theme.scss` is new).

> Aside from the branch conflicts, any pending work before we can merge this into master?

Just the rebase which requires converting a few front-end changes from master. All things going smoothly, I'm hoping to have time to do this tomorrow.

**Comment by jasoncharnes** [comment]
@spohlenz I just wanted to say: thank you for your work on this. 🙏

**Comment by swrobel** [comment]
FYI Webpacker engine docs seem to have improved a lot lately: https://github.com/rails/webpacker/blob/master/docs/engines.md

I know it's already on your radar, but I'd love to see this eventually as I'm trying to run a sprockets-free Rails 6 app.

**Comment by spohlenz** [comment]
> FYI Webpacker engine docs seem to have improved a lot lately: https://github.com/rails/webpacker/blob/master/docs/engines.md
> 
> I know it's already on your radar, but I'd love to see this eventually as I'm trying to run a sprockets-free Rails 6 app.

@swrobel Definitely a goal that I share. I don't know if webpacker's engine support has improved sufficiently (I will have to revisit that). However hopefully I might be able to help steer it in the right direction now.

One other approach I am exploring is enable building a custom pack inside the host app and then inject that inside Trestle.

> Also, it'd be worth mentioning somewhere in the README that either sass-rails or sassc-rails needs to be included in your Gemfile or rails generate trestle:install will fail.

I've created a new issue to track this at #242. Ideally Trestle will just handle this automatically and not create the `.scss` files in this case.

**Comment by spohlenz** [comment]
This branch has now been merged, along with similar branches in trestle-auth (TrestleAdmin/trestle-auth#18) and trestle-search (TrestleAdmin/trestle-search#9).

Thank you all for your feedback on this update. This has been a bit of a roadblock for some time so I'm very happy to finally have it merged in.

**Pull request merged**
