### PR TITLE
Add a json_text_field form element for rich editing json blobs

### PR DESCRIPTION
**Pull request by airhorns**
This adds a rich text area control for JSON fields in automatic forms and a `json_text_area` tag helper to render it on demand. A quick demo:

https://www.loom.com/share/85ed1ed9cf344e91b9301d8c981259d0

It uses the [jsoneditor](https://www.npmjs.com/package/jsoneditor) npm package to do all the fancy stuff, and marshals the json to and from a hidden input storing it as a string.

In my admin we're managing a bunch of different JSON blobs and it's nice to have some rich UI to at least tell you if you've written broken syntax, as well as having nice syntax highlighting and an auto formatter. No need to waste human time doing work machines can do. I'm not sure how prevalent JSON/JSONB fields are in other admins but both MySQL and Postgres support the field type now, and Rails' support has come a long way, so I feel like this is likely to be handy for others.

### Concerns

1. Bundle size. `jsoneditor` is huge and the Trestle JS bundle goes from 0.35 MB to 1.2 MB with this change. There's a minimal version of `jsoneditor` that's much smaller but drops a lot of features and ends up being a lot closer to a text area than something useful. To address this, I could move the jsoneditor code out into a different bundle and only grab it on demand, but that adds more complexity to the build pipeline and assets configuration. For an internal admin, I feel like a big bundle is ok-ish, so I figured I'd open this and see what folks thought before doing a bunch more complicated work. I also think it might make sense to use the bundled `ace` editor for other text areas as well if there are features other text editors might appreciate. 

2. JSON mass assignment in Rails. Because Trestle does things the Rails way, it calls `#update_attributes` on the model object with the params pretty much untouched from the form submit. In the case of a plain old `text_area`, which is what one might use before this change, and in the case of this `json_text_area`, the JSON comes in as a string in the params. Rails doesn't have any magic that parses that string at the controller layer or the model layer before assigning it, so without any extra setup, submitting JSON in a text area or a `json_text_area` saves the raw json as an escaped string to the column. If this happens, it looks like this:

https://www.loom.com/share/78d2676a41064da6951019ff1aaa0fcf

which is undesirable. To fix this, you have to teach some piece of the stack to parse the string on the way in. I think I could potentially do this in Trestle, but it sets a kind of nasty precedent of params manipulation on the way through the ResourceController that nothing else has needed to do yet. Instead, I did it in user land with Rails' attribute system:

```ruby
# app/models/concerns/jsonb_type_value.rb
class JsonbTypeValue < ActiveModel::Type::Value
  def type
    :jsonb
  end

  def cast_value(value)
    case value
    when String
      ActiveSupport::JSON.decode(value) rescue nil
    when Hash
      value
    end
  end

  def serialize(value)
    case value
    when Hash
      ActiveSupport::JSON.encode(value)
    else
      super
    end
  end

  def changed_in_place?(raw_old_value, new_value)
    cast_value(raw_old_value) != new_value
  end
end
```

and then in the model:

```ruby
# app/models/property.rb
class Property < ApplicationRecord
  attribute :internal_test_options, JsonbTypeValue.new
end
```

That doodad forces newly assigned strings to be decoded into hashes with a `JSON.decode`. Without this piece in place the `json_text_field` will be kind of broken which sucks, but I feel like this is the most explicit way to fix it. At minimum we could put this in a wiki page, and potentially warn or raise if this behaviour isn't detected on the model?

### Notes

To get `jsoneditor` to webpack properly I had to add `resolve-url-loader`. It rewrites relative urls in sass includes that change the director paths would be relative to to be absolute. Later loaders expect relative paths to be relative to the very first file imported, which isn't always in the same place. See https://www.npmjs.com/package/resolve-url-loader for more info.

This PR is very much a request for comments. I'm happy to move this functionality out into a gem if it seems to esoteric for the core, but I do think things just working for everyone else using JSON columns would be nice too!

### CODE REVIEW

**Comment by spohlenz** [comment]
First off, thank you for the work you've put into this. I can definitely see it being very useful (a couple of examples from previous issues #18, #199) and I would love to have it as part of the Trestle ecosystem.

As you mentioned though, primarily due to the very large size of `jsoneditor` I think it would be better suited as a separate gem. I'd be more than happy to provide any feedback or assistance required for that, and to add it to the Trestle README when it's ready to go.

**Comment by airhorns** [comment]
Ok, I'll peel it out! :)

**Comment by tcd** [comment]
@airhorns Any update on a gem for this? I'd definitely be interested in helping if it hasn't already been done.

**Comment by airhorns** [comment]
https://github.com/airhorns/trestle-jsoneditor is a thing! Note there's an extra installation step if you have a vanilla Rails app right now outlined here: https://github.com/airhorns/trestle-jsoneditor/issues/2

**Pull request closed without merging**
